- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - vim
          - tmux
